studySpec:
  metrics:
  - metricId: accuracy
    goal: MAXIMIZE # TODO: parameters
  parameters:
  - parameterId: max_iter
    discreteValueSpec:
        values:
            - 10
            - 20
  - parameterId: alpha
    scaleType: UNIT_LOG_SCALE
    doubleValueSpec:
        minValue: 1.0e-4
        maxValue: 1.0e-1
  algorithm: ALGORITHM_UNSPECIFIED # results in Bayesian optimization
trialJobSpec:
  workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/qwiklabs-asl-00-61116abbd0d9/asl-artifact-repo/trainer_image:latest
      args:
      - --job_dir=gs://qwiklabs-asl-00-61116abbd0d9-kfp-artifact-store/jobs/forestcover_tuning_20240423_092839
      - --training_dataset_path=gs://qwiklabs-asl-00-61116abbd0d9-kfp-artifact-store/data/training/dataset.csv
      - --validation_dataset_path=gs://qwiklabs-asl-00-61116abbd0d9-kfp-artifact-store/data/validation/dataset.csv
      - --hptune
