displayName: taxifare_20240423_093924
studySpec:
  metrics:
  - metricId: val_rmse # TODO: Your code goes here
    goal: MINIMIZE
  parameters:
  - parameterId: lr
    doubleValueSpec:
      minValue: 0.0001
      maxValue: 0.01
    scaleType: UNIT_LOG_SCALE
  - parameterId: nbuckets
    integerValueSpec:
      minValue: 10
      maxValue: 25
    scaleType: UNIT_LINEAR_SCALE
  - parameterId: batch_size
    discreteValueSpec:
      values:
        - 15
        - 30
        - 50
  algorithm: ALGORITHM_UNSPECIFIED # results in Bayesian optimization
trialJobSpec:
  baseOutputDirectory:
    outputUriPrefix: gs://qwiklabs-asl-00-61116abbd0d9/taxifare_20240423_093924
  workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    pythonPackageSpec:
      args:
      - --train_data_path=gs://qwiklabs-asl-00-61116abbd0d9/taxifare/data/taxi-train*
      - --eval_data_path=gs://qwiklabs-asl-00-61116abbd0d9/taxifare/data/taxi-valid*
      - --batch_size=15
      - --num_examples_to_train_on=100
      - --num_evals=10
      - --nbuckets=10
      - --lr=0.001
      - --nnsize=32 8
      executorImageUri: us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-12.py310:latest
      packageUris:
      - gs://qwiklabs-asl-00-61116abbd0d9/taxifare/taxifare_trainer-0.1.tar.gz
      pythonModule: trainer.task
    replicaCount: 1
